import { createApp } from 'vue'
import { createPinia } from 'pinia'
import router from './router'
import App from './App.vue'

// FontAwesome
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faBuilding as farBuilding
} from '@fortawesome/free-regular-svg-icons'
import {
  faBuilding,
  faBuildingCircleArrowRight,
  faChartSimple,
  faChartBar,
  faChartLine,
  faChartPie,
  faPenToSquare,
  faPen,
  faPlus,
  faGear,
  faHouse,
  faArrowRightFromBracket,
  faArrowLeft,
  faCalendarDays,
  faUsers,
  faUsersGear,
  faUser,
  faUserPlus,
  faUserClock,
  faCircleExclamation,
  faCircleCheck,
  faCircleInfo,
  faClock,
  faEnvelopeCircleCheck,
  faEye,
  faEyeSlash,
  faLock,
  faTrash,
  faTriangleExclamation,
  faClipboardList,
  faClipboardCheck,
  faDoorOpen,
  faScrewdriverWrench,
  faRotate,
  faRedo,
  faSitemap,
  faBook,
  faShieldHalved,
  faFilter,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faCheckDouble,
  faImage,
  faPrint,
  faSpinner,
  faCity,
  faFileCirclePlus,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  farBuilding,
  faBuilding,
  faBuildingCircleArrowRight,
  faChartSimple,
  faChartBar,
  faChartLine,
  faChartPie,
  faPenToSquare,
  faPen,
  faPlus,
  faGear,
  faHouse,
  faArrowRightFromBracket,
  faArrowLeft,
  faCalendarDays,
  faUsers,
  faUsersGear,
  faUser,
  faUserPlus,
  faUserClock,
  faCircleExclamation,
  faCircleCheck,
  faCircleInfo,
  faClock,
  faEnvelopeCircleCheck,
  faEye,
  faEyeSlash,
  faLock,
  faTrash,
  faTriangleExclamation,
  faClipboardList,
  faClipboardCheck,
  faDoorOpen,
  faScrewdriverWrench,
  faRotate,
  faRedo,
  faSitemap,
  faBook,
  faShieldHalved,
  faFilter,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faCheckDouble,
  faImage,
  faPrint,
  faSpinner,
  faCity,
  faFileCirclePlus,
)

const app = createApp(App)
app.use(createPinia())
app.use(router)
app.component('FontAwesomeIcon', FontAwesomeIcon)
app.mount('#app')
